build-image:
	docker build -t registry.digitalocean.com/main/lexi-drift-lexify .

push-image:
	docker push registry.digitalocean.com/main/lexi-drift-lexify

ssh:
	ssh root@188.245.164.95

up:
	pnpm dev