services:
  video-converter:
    image: registry.digitalocean.com/main/lexi-drift-video
    ports:
      - "8080:8080"
    environment:
      - INFISICAL_TOKEN
    deploy:
      resources:
        limits:
          cpus: '1.500'
          memory: 500M
